version: '3.8'

services:
  umbraco-site:
    image: umbraco/umbraco:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:80"
    depends_on:
      - sql-edge
      - redis-cache
      - rabbitmq
      - mongodb
      - aspnet-api
    networks:
      - app-network

  sql-edge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  redis-cache:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  aspnet-api:
    image: mcr.microsoft.com/dotnet/aspnet:7.0 # LTS version for ASP.NET
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"
    depends_on:
      - sql-edge
      - rabbitmq
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
