services:
  umbwebsite:
    image: ${DOCKER_REGISTRY-}umb-website
    restart: unless-stopped
    build:
      context: .
      dockerfile: UmbWebsite/Dockerfile
    depends_on:
      - sql-db    
    networks:
      - app-network

  api:
    image: ${DOCKER_REGISTRY-}api
    restart: unless-stopped
    build:
      context: .
      dockerfile: DemoApi/Dockerfile
    depends_on:
      - sql-db    
    networks:
      - app-network
 
  message-processor:
    image: ${DOCKER_REGISTRY-}message-processor
    restart: unless-stopped
    build:
      context: .
      dockerfile: MessageProcessor/Dockerfile
    depends_on:
      - sql-db    
    networks:
      - app-network

  sql-db:
    container_name: ${DOCKER_REGISTRY-}sql-db
    restart: unless-stopped
    build:
      context: .
      dockerfile: SQLDb/Dockerfile
    ports:
     - "1433:1433"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network    

networks:
  app-network:
    driver: bridge

